# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: notifail
builds:
  - id: default
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    main: .
    binary: notifail
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    hooks:
      post:
        - make man VERSION={{.Version}} COMMIT={{.ShortCommit}} DATE={{.Date}}
brews:
  - install: |
      bin.install "notifail"
      man1.install Dir.glob('notifail*.1')
    tap:
      owner: kyoh86
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kyoh86/notifail
    description: Notify failure over OS notification drivers
    license: MIT
nfpms:
  - builds:
      - default
    maintainer: kyoh86 <me@kyoh86.dev>
    homepage: https://github.com/kyoh86/notifail
    description: Notify failure over OS notification drivers
    license: MIT
    formats:
      - apk
      - deb
      - rpm
archives:
  - id: gzip
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
      - notifail.1
